module.exports = [
  //   { name: "Afghanistan", code: "AF" },
  //   { name: "Åland Islands", code: "AX" },
  //   { name: "Albania", code: "AL" },
  //   { name: "Algeria", code: "DZ" },
  //   { name: "American Samoa", code: "AS" },
  //   { name: "AndorrA", code: "AD" },
  //   { name: "Angola", code: "AO" },
  //   { name: "Anguilla", code: "AI" },
  //   { name: "Antarctica", code: "AQ" },
  //   { name: "Antigua and Barbuda", code: "AG" },

  //   { name: "אבא", code: "אב" },
  //   { name: "אבלה", code: "אל" },
  //   { name: "בגדים", code: "בד" },
  //   { name: "תכשיטים", code: "תש" },
  //   { name: "תמונות", code: "תמ" },

  { name: "חנויות" },
  { name: "בגדים" },
  { name: "מלונות" },
  { name: "ארועים" },
  { name: "מסעדות" },
  { name: "כל הקטגוריות" },
  { name: "ספורט" },
  { name: "קפטריות" },
  { name: "נעליים" },
  { name: "תכשיטים" },
  { name: "רהיטים" },
  { name: "מסעדות" },
  { name: "נעלי גיל" },
  { name: "מסעדות" },
  { name: "מסעדת הים" },
];
